import { Poppins } from "next/font/google";
import "./globals.css";

import { Lato } from 'next/font/google'
 
const lato = Lato({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

const poppins = Poppins({subsets: ["latin"], weight: ['400', '700']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>

        {children}
      </body>
    </html>
  );
}
